### ISSUE TITLE
Removing 'thinlinc_server_bundle' 'breaks' project organization

### ISSUE THREAD

**Issue by Thulium-Drake** [cendio/ansible-role-thinlinc-server#42]
Hi there,

In fad51d0 the ```thinlinc_server_bundle``` variable was removed, which allowed to place the zip file with the Thinlinc software in a custom location inside the ```playbooks/files``` folder (in my case ```playbooks/files/thinlinc``` as I have lots of files for different purposes that I distribute)

However, now I 'must' place the zip file in the top dir.

Can you please revert this? As it removes flexibility in where files can be stored.

**Comment by samhed** [comment]
Thanks for sharing your use case. I think we didn't consider the fact that you might use it for that purpose.

Would you mind having a look at this @aeneby? Do you think it would be a good idea to have an optional parameter for a directory in which to look for the server-zip?

**Comment by aeneby** [comment]
I think that's a reasonable request. We should probably have an optional parameter for the whole path (including filename) though, with a sensible default if not specified. Otherwise the next issue is going to be from someone wanting to rename the server bundle to something else.

@samhed assign to me if you like, I'll have a look.

**Comment by samhed** [comment]
Good thinking
