### ISSUE TITLE
Problem with handler restart vsmserver

### ISSUE THREAD

**Issue by pewo** [cendio/ansible-role-thinlinc-server#7]
When uppgrading from an older version of thinlinc using this role.
I got an error when the handler ran.

```
RUNNING HANDLER [ansible-role-thinlinc-server : restart vsmserver]
Thursday 17 September 2020 10:50:33 +0200 (0:00:00.611)    0:02:09.388 ****
fatal: [myserver]; FAILED! => {"changed": false, "msg": "Service is in unknown state", "status": {}}

```

Trying to do this manually on the server got another error message...

```
# systemctl restart vsmserver.service
Failed to restart vsmserver.service: Access denied

# systemctl status vsmserver.service
Failed to get properties: Access denied
```
After doing: 
```
# systemctl daemon-reload
# systemctl restart vsmserver
# systemctl restart vsmagent
```
Everything works.

**Comment by samhed** [comment]
In ThinLinc 4.12 we moved our services to use systemd instead of old SysV and unfortunately, as part of this, we introduced a problem on RHEL 7 machines:

https://www.cendio.com/bugzilla/show_bug.cgi?id=7526

It will be fixed in the upcoming ThinLinc release, and is not limited to this ansible project.
